### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by m0unt4ine3r** [m0unt4ine3r/hwsort#1]
- [ ] change for Set3
     - [ ] change for set n
- [x] improve fuzzy searching
- [x] refactor to functions
- [x] provide options to only run sections
     - [ ] pick and choose multiple sections
- [ ] better documentation
- [ ] redo variables
- [ ] fix calculations
- [ ] something for adding missing directories
- [ ] handling full project submission
- [ ] more intelligence with file checking
     - [ ] check files for name?
     - [ ] check files for title?
- [ ] better way to set student, report, and error vars outside initial run
- [ ] integration with perl script?
- [ ] verbosity levels
- [ ] support for other editors/ides
- [ ] interactivity
